/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Token usage with cache support */
export interface TokenUsage {
  inputTokens: number
  outputTokens: number
  cacheCreationInputTokens?: number
  cacheReadInputTokens?: number
}
/** Enhanced Claude message with full content support */
export interface ClaudeMessage {
  messageId: string
  sessionId: string
  role: string
  content: string
  timestamp: string
  rawContent: string
  hasThinking: boolean
  hasToolUse: boolean
  hasImages: boolean
  parentId?: string
  model?: string
  stopReason?: string
  inputTokens?: number
  outputTokens?: number
  cacheCreationTokens?: number
  cacheReadTokens?: number
  isSidechain?: boolean
  userType?: string
}
/** Session summary */
export interface ClaudeSession {
  sessionId: string
  filePath: string
  messageCount: number
  userMessageCount: number
  assistantMessageCount: number
  firstTimestamp?: string
  lastTimestamp?: string
  totalInputTokens?: number
  totalOutputTokens?: number
  hasThinking: boolean
  hasToolUse: boolean
  cwd?: string
}
/** Parse Claude Code session file and return all messages */
export declare function parseClaudeSession(filePath: string): Array<ClaudeMessage>
/** Get session summary with enhanced statistics */
export declare function getSessionSummary(filePath: string): ClaudeSession
export declare function countLines(filePath: string): number
export declare function readLines(filePath: string): Array<string>
export declare function readLinesWithPattern(filePath: string, pattern: string): Array<string>
export declare function getFileInfo(filePath: string): string
